# Generated by Django 4.2.2 on 2023-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0002_profile_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
