# Generated by Django 4.2.2 on 2023-06-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0002_profile_is_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=2000)),
                ("created_date", models.DateTimeField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
            ],
        ),
    ]
