# Generated by Django 4.2.2 on 2023-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0003_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.TextField(max_length=2000)),
                ("text", models.TextField(max_length=2000)),
                ("created_date", models.DateTimeField()),
            ],
        ),
    ]
