# Generated by Django 4.2.2 on 2023-06-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0003_class_is_started"),
        ("lms_app", "0004_announcement"),
    ]

    operations = []
