# Generated by Django 4.2.2 on 2023-06-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0006_messages_delete_announcement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages", old_name="user", new_name="user_id",
        ),
    ]
