# Generated by Django 4.2.2 on 2023-06-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0007_rename_user_messages_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="in_class",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_app.class",
            ),
            preserve_default=False,
        ),
    ]
