# Generated by Django 4.2.2 on 2023-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0008_material_in_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="created_date",
            field=models.DateTimeField(null=True),
        ),
    ]
