# Generated by Django 4.2.2 on 2023-07-06 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_app', '0010_forumthread_forumpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumPost',
            new_name='ForumAnswer',
        ),
        migrations.AddField(
            model_name='forumthread',
            name='text',
            field=models.TextField(default='a', max_length=2000),
            preserve_default=False,
        ),
    ]
