# Generated by Django 4.2.2 on 2023-07-15 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lms_app", "0011_rename_forumpost_forumanswer_forumthread_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("light_theme", models.BooleanField(default=True)),
                ("highlight_color", models.TextField(default="#0000FF", max_length=7)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
