# Generated by Django 4.2.2 on 2023-07-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0012_colour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colour",
            old_name="highlight_color",
            new_name="highlight_colour",
        ),
    ]
