# Generated by Django 4.2.2 on 2023-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0013_rename_highlight_color_colour_highlight_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="class", name="live_link", field=models.URLField(blank=True),
        ),
    ]
