# Generated by Django 4.2.2 on 2023-07-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0014_class_live_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="class", name="live_link",),
    ]
