# Generated by Django 4.2.2 on 2023-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0015_remove_class_live_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="class", name="live_link", field=models.URLField(blank=True),
        ),
    ]
