# Generated by Django 4.2.2 on 2023-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0016_class_live_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="live_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
