# Generated by Django 4.2.2 on 2023-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0018_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profilepicture/"),
        ),
    ]
