# Generated by Django 4.2.2 on 2023-07-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
