# Generated by Django 4.2.2 on 2023-07-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0020_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                ("created_date", models.DateTimeField(null=True)),
                ("due_date", models.DateTimeField(null=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lms_app.class"
                    ),
                ),
            ],
        ),
    ]
